### ISSUE TITLE
Error starting downloads can not open file path error

### ISSUE THREAD

**Issue by Askadelion** [AdriaanBoshoff/Youtube-Downloader#1]
https://github.com/AdriaanBoshoff/Youtube-Downloader/blob/f29afc5efa573e62dd4fa0a2dff08e7a2bf0cb1b/uDownloadListBoxItem.pas#L122

This line is not to be used on foreign computers here you should determine the path over ExtractFilePath

![grafik](https://user-images.githubusercontent.com/41443013/198880023-b9465cd1-2b17-4f8d-bb20-a2436d7369ac.png)

**Comment by AdriaanBoshoff** [comment]
Yes I forgot to change this. It was for testing. I will add the icon to the resources soon and load from there.

**Comment by Askadelion** [comment]
all good, for converting the video is still missing a status process, maybe you make the effort and add something like this

But is a Cool Idea 
Continue Have fun

**Comment by AdriaanBoshoff** [comment]
Alright. Fixed it. I'm looking forward to expanding this to more features. I just wanted to see how basic I could make it for personal use. I'll eventually also use the command line tool to get supported formats for downloading.
